### ISSUE TITLE
Teams card broken after iOS app update

### ISSUE THREAD

**Issue by Jessicaward** [AntoineGa/Seq.App.Teams#40]
Myself and a colleague updated our Teams app to _4.15.1_, now when Seq sends an alert to Teams, the card doesn't show up. We still get the notification, but opening the message shows a blank screen.

Other cards are working fine (from other apps), and it was working fine before the app update.

I'll attach a screenshot in the comments.

**Comment by Jessicaward** [comment]
![image](https://user-images.githubusercontent.com/13490377/188613853-d03157d3-e8e2-49bc-b9e8-ebd83b41d6cb.jpeg)

**Comment by Jessicaward** [comment]
![image](https://user-images.githubusercontent.com/13490377/188614045-bf373a22-c37d-4678-b7ee-cd306eb5fe52.jpeg)

**Comment by Jessicaward** [comment]
Not sure if maybe something in the iOS Teams app has changed, which requires a change to this app? Happy to provide any additional feedback, help out with changes or answer any questions. Thanks!

**Comment by nblumhardt** [comment]
Hi Jessica,

I've spotted:

* https://techcommunity.microsoft.com/t5/teams-developer/message-cards-not-showig-on-iphone/m-p/3619361#M6340
* https://www.reddit.com/r/MicrosoftTeams/comments/x7d3nh/blank_card_notifications_on_iphone/

So unfortunately, it looks like an issue with a broken Teams app rather than something we can try to fix here.

Hope this helps, and good luck with it!

Nick

**Comment by Jessicaward** [comment]
Hi,

Thanks for that! I did think it was maybe a Teams bug, just couldn't find any reports of it at the time.

I'll raise a case with Microsoft.

Thanks!
